[2023-08-25T09:48:33.279+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT_analytics_video_games.clean_destination_postgresql scheduled__2023-08-24T00:00:00+00:00 [queued]>
[2023-08-25T09:48:33.284+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT_analytics_video_games.clean_destination_postgresql scheduled__2023-08-24T00:00:00+00:00 [queued]>
[2023-08-25T09:48:33.285+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-08-25T09:48:33.291+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): clean_destination_postgresql> on 2023-08-24 00:00:00+00:00
[2023-08-25T09:48:33.295+0000] {standard_task_runner.py:57} INFO - Started process 3306 to run task
[2023-08-25T09:48:33.298+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ELT_analytics_video_games', 'clean_destination_postgresql', 'scheduled__2023-08-24T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/3_ETL_mysql_postgresql_dag/ELT_dag.py', '--cfg-path', '/tmp/tmptdxgc_zo']
[2023-08-25T09:48:33.300+0000] {standard_task_runner.py:85} INFO - Job 37: Subtask clean_destination_postgresql
[2023-08-25T09:48:33.337+0000] {task_command.py:415} INFO - Running <TaskInstance: ELT_analytics_video_games.clean_destination_postgresql scheduled__2023-08-24T00:00:00+00:00 [running]> on host 4059ad9a5b0d
[2023-08-25T09:48:33.384+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Willis' AIRFLOW_CTX_DAG_ID='ELT_analytics_video_games' AIRFLOW_CTX_TASK_ID='clean_destination_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2023-08-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-24T00:00:00+00:00'
[2023-08-25T09:48:33.385+0000] {sql.py:274} INFO - Executing:  TRUNCATE TABLE sales;
[2023-08-25T09:48:33.393+0000] {base.py:73} INFO - Using connection ID 'postgresql_connection' for task execution.
[2023-08-25T09:48:33.402+0000] {base.py:73} INFO - Using connection ID 'postgresql_connection' for task execution.
[2023-08-25T09:48:33.453+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres_destination_server" to address: Name or service not known

[2023-08-25T09:48:33.462+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ELT_analytics_video_games, task_id=clean_destination_postgresql, execution_date=20230824T000000, start_date=20230825T094833, end_date=20230825T094833
[2023-08-25T09:48:33.468+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 37 for task clean_destination_postgresql (could not translate host name "postgres_destination_server" to address: Name or service not known
; 3306)
[2023-08-25T09:48:33.510+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-25T09:48:33.527+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
